export const UsersMock = [
  {
    createdAt: new Date(),
    isAdmin: true,
    agente: 'SeedAdmin',
    nombre: 'Seed User',
    direccion: 'Calle Falsa 123',
    telefono: 1234567,
    latitud: -28.978690147764837,
    longitud: -61.48905321096909,
    documento: 45123456,
    email: 'seedUser@mail.com',
    password: 'P@ssw0rd',
    razonSocial: 'Café los Angelitos',
    impuesto: 'string',
    provincia: '',
    localidad: '',
    codigoPostal: '5529',
    domicilioInstal: 'Urquiza 3560 1°A',
    localidadInstal: 'Maipu',
    telefonoInstal: 1234567,
    emailInstal: 'seedUser@mail.com',
    observaciones: 'Seed para usuario administrador',
    senalConexion: '00',
    equiposId: 'no',
    serviciosId: 'no',
  },
];
